### ISSUE TITLE
Version string with letter v?

### ISSUE THREAD

**Issue by janArb** [pbalu-code/ansible-postgresql#2]
Hey,

you really intended to use `v2.3.0` as version string, i.e. including letter 'v' as prefix? I was very surprised by that and would have expected `2.3.0` without that prefix. Does that has any advantages I don't know?

Best regards
Jan

**Comment by pbalu-code** [comment]
It is not mandatory for the upcoming versions.

**Comment by janArb** [comment]
This is a larger discussion in the standard itself, continue there: https://github.com/semver/semver/issues/204#issuecomment-1386618567
