### ISSUE TITLE
Postgres 12 installation fails for Red Hat 8.8

### ISSUE THREAD

**Issue by janArb** [pbalu-code/ansible-postgresql#5]
Hi,

pg_repack12 is not available anymore for Red Hat 8.8 (I guess a dependency issue).

```
TASK [pbalucode.postgresql : Install pg_repack] ********************************
fatal: [localhost]: FAILED! => {"changed": false, "failures": ["No package pg_repack12 available."], "msg": "Failed to install some of the specified packages", "rc": 1, "results": []}
```

I created pull request https://github.com/pbalu-code/ansible-postgresql/pull/4 to skip the installation for Red Hat 8.8 (and higher). This solves the issue.

In the README.md was already mentioned the that pg_repack cannot be used for postgres 14. 
I updated this to reflect the new restriction for Red Hat 8.8.
I was very confused by the heading syntax in the whole README.md and updated it to the more readable version (number of signs equals level) everywhere.

PS: May I ask for a new release after pulling, please?

**Comment by pbalu-code** [comment]
Thanks for the support. I have accepted the request.
