### ISSUE TITLE
Red Hat 9 fails

### ISSUE THREAD

**Issue by janArb** [pbalu-code/ansible-postgresql#6]
`FAILED! => {"changed": false, "failures": ["No package python38-psycopg2 available."], "msg": "Failed to install some of the specified packages", "rc": 1, "results": []}`

**Comment by janArb** [comment]
Red Hat 9 is using Python 3.9., i.e. my fix should work. I wait for QA for Ubuntu, Red Hat 8 and Red Hat 9. I'm still unsure if my fix might break something for Red Hat 8 again. If so, I still think my fix should be applied and then this other issue would need another approach.

**Comment by janArb** [comment]
Created ansible-postgresql/pull/7 to solve this issue...

**Comment by pbalu-code** [comment]
Thank you. I have merged your fix.
